jasp-stats/jaspRegression

R/commonglm.R
A twin PR to https://github.com/jasp-stats/jasp-desktop/pull/4098
=> Tjur R-squared calculation

R/correlation.R, inst/qml/Correlation.qml
Corresponding PR to https://github.com/jasp-stats/jasp-desktop/pull/4209
=> Enable partial correlations

R/regressionlogistic.R, inst/qml/RegressionLogistic.qml
Here is the PR for the performance plots that are already merged into jasp-desktop.
=> Add performance plots for logistic regression

inst/help/regressionlinearbayesian.md, inst/help/regressionlinearbayesian_nl.md, inst/qml/RegressionLinearBayesian.qml
Implements changes done to `jasp-desktop/stable`: https://github.com/jasp-stats/jasp-desktop/pull/4257
=> berouilli -> bernoulli and update bayesian linear regression help files

R/regressionlinearbayesian.R
changes in the unit test aren't copied because the repo doesn't contain any tests yet.
=> counterpart of jasp-stats/jasp-desktop/pull/4226

R/correlationbayesian.R, inst/qml/CorrelationBayesian.qml
Fixes #9 
Changes to test files were not copied since the repo doesn't contain the tests yet.
=> counterpart of jasp-stats/jasp-desktop#4327

inst/help/regressionlinear.md, inst/help/regressionlinear_nl.md, inst/help/regressionlogistic.md, inst/help/regressionlogistic_nl.md, inst/qml/RegressionLinear.qml, inst/qml/RegressionLogistic.qml
Brings changes up to date with stable:
- https://github.com/jasp-stats/jasp-desktop/pull/4168
- https://github.com/jasp-stats/jasp-desktop/pull/4179
=> Hunting down stable pr

R/regressionlinear.R
Fixes jasp-stats/jasp-issues#1023
=> Linear Regression does not give ANOVA results in dutch

inst/qml/RegressionLinear.qml
Following the discussion in jasp-stats/INTERNAL-jasp#1155
Counterpart of https://github.com/jasp-stats/jasp-desktop/pull/4386
=>  Disallow factors for covariates in linear regression

R/regressionlinearbayesian.R
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1263
=> explicitly load BAS namespace when retrieving object from state

R/correlationbayesian.R, tests/testthat/test-correlationbayesian.R
Fixes https://github.com/jasp-stats/jasp-issues/issues/1204
=> Meaningful error message when posterior is too peaked

R/regressionlinear.R
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1355
based on https://forum.cogsci.nl/discussion/7082/wls-weights-option#latest
=> Adjust lower limit for wls weights

DESCRIPTION
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1276
=> add gridGraphics to the DESCRIPTION

inst/qml/RegressionLinear.qml
fixed https://github.com/jasp-stats/jasp-issues/issues/1198
=> remove "vs." in "residuals vs. histogram"

inst/help/regressionlinear.md, inst/help/regressionlinear_nl.md
Fixes https://github.com/jasp-stats/jasp-issues/issues/1495
I didn't add any information about when to treat an ordinal variable as continuous or categorical, but I'm not sure if there is a good recommendation for that.
=> Helpfile: add info about factors

R/correlation.R
fixes https://github.com/jasp-stats/jasp-issues/issues/1523
=> Pairwise plots should not crash with ordinal variables

R/regressionlinear.R, tests/testthat/test-regressionlinear.R
fixes https://github.com/jasp-stats/jasp-issues/issues/1537
=> Fix summary table when categorical predictors are used

R/regressionlogistic.R, inst/qml/RegressionLogistic.qml, tests/testthat/test-regressionlogistic.R
fixed https://github.com/jasp-stats/jasp-issues/issues/1471
fixed https://github.com/jasp-stats/jasp-issues/issues/1515
=> fix logistic regression confusion matrix and add multicollinearity table

R/bfCommon.R, R/correlation.R, tests/testthat/test-correlation.R
fixes https://github.com/jasp-stats/jasp-test-release/issues/1711
also fixes point 1 in https://github.com/jasp-stats/jasp-test-release/issues/1714
and adds a test
=> Fix bootstrapped partial correlation with a lot of missings

R/regressionlinear.R, tests/testthat/test-regressionlinear.R
Requested via email by @herberthoijtink
=> Add bootstrapped p-value to linear regression

R/correlation.R, inst/Upgrades.qml, inst/help/Correlation.md, inst/help/Correlation_nl.md, inst/qml/Correlation.qml, tests/testthat/test-correlation.R
fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1772
=> Clarify partial correlations

inst/qml/common/GlmInputComponent.qml
fixed: https://github.com/jasp-stats/jasp-test-release/issues/1835
=> remove weights as a title for the input variable panel

DESCRIPTION, inst/Description.qml, inst/Upgrades.qml
fixes https://github.com/jasp-stats/jasp-test-release/issues/1834
=> fix version numbers

inst/help/RegressionLinear.md, inst/help/RegressionLinear_nl.md, inst/help/RegressionLogistic.md, inst/help/RegressionLogistic_nl.md
related to https://github.com/jasp-stats/jasp-issues/issues/1800
=> add references to help files for VIF

R/glmClassical.R, R/glmCommonFunctions.R, inst/Upgrades.qml, inst/qml/GeneralizedLinearModel.qml, inst/qml/common/GlmInputComponent.qml, inst/qml/common/GlmResidualAnalysisPlotsComponent.qml, tests/testthat/test-generalizedlinearmodel.R
fixed https://github.com/jasp-stats/INTERNAL-jasp/issues/1939
=> rename options for the glm analysis

R/glmClassical.R, tests/testthat/test-generalizedlinearmodel.R
fixed https://github.com/jasp-stats/jasp-test-release/issues/1962
=> fixed crash when confidence intervals are requested for an interncept-only model

R/correlationbayesian.R
fixes https://github.com/jasp-stats/jasp-test-release/issues/1971
=> fix prior posterior plot in bayesian correlations

R/commonglm.R, R/regressionlinear.R, R/regressionlogistic.R
fixes https://github.com/jasp-stats/jasp-issues/issues/1829
=> add missing `gettext`s

R/commonglm.R, R/regressionlogistic.R, inst/Upgrades.qml, inst/qml/RegressionLogistic.qml, tests/testthat/test-regressionlogistic.R, tests/testthat/test-regressionlogisticVerification.R
fixed https://github.com/jasp-stats/INTERNAL-jasp/issues/1938
=> renamed options for logistic regression

R/correlation.R, R/correlationbayesian.R, R/regressionlinear.R, po/R-de.po, po/R-es.po, po/R-gl.po, po/R-ja.po, po/R-jaspRegression.pot, po/R-nl.po, po/R-pt.po, po/R-ru.po, po/R-zh_Hans.po
Part of https://github.com/jasp-stats/INTERNAL-jasp/issues/2125
_Note: might need to pay attention to merge order.To ensure that it does not conflict or overwrite with other translation PRs from Weblate，the translate Github action should be run manually once this was merged._
=> Add position in placeholders inside gettextf

inst/Upgrades.qml, inst/qml/RegressionLogistic.qml
… default
fixed: https://github.com/jasp-stats/jasp-issues/issues/1814
=> logistic regression will not add interaction terms between factors by default

R/regressionlinear.R
fixes https://github.com/jasp-stats/jasp-issues/issues/1989
admittedly I am not the proudest of the fix, as it requires to load the dataset a second time. However the alternative would be to either pass around the dataset right inside of the code that computes the diagnostics and/or removing uncomplete cases elsewhere than when we read the data for analysis, which would be a more involved rewrite.
=> fix case ID in casewise diagnostics with missing data

R/correlation.R
fixes https://github.com/jasp-stats/jasp-issues/issues/2022
=> fix state issue with correlations

R/regressionlinear.R, tests/testthat/_snaps/regressionlinear/marginal-effect-of-contcor1-on-contnormal.svg, tests/testthat/_snaps/regressionlinear/marginal-effect-of-contgamma-on-contnormal.svg, tests/testthat/test-regressionlinear.R
fixes https://github.com/jasp-stats/jasp-issues/issues/2016
and adds a unit test
=> marginal effect plots should not crash on models with interactions

R/regressionlinear.R
fixes https://github.com/jasp-stats/jasp-test-release/issues/2295
fixes https://github.com/jasp-stats/jasp-test-release/issues/2296
=> Linear regression - 0.17.2 release fixes

inst/qml/Correlation.qml
fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/2414
=> Effect Size -> Effect size

R/generalizedlinearmodel.R, R/glmCommonFunctions.R
fixes https://github.com/jasp-stats/jasp-test-release/issues/2471
fixes https://github.com/jasp-stats/jasp-test-release/issues/2472
fixes https://github.com/jasp-stats/jasp-test-release/issues/2473
=> Release fixes for GLMs

R/commonglm.R, R/glmCommonFunctions.R, R/regressionlinear.R, R/regressionlogistic.R
fixes https://github.com/jasp-stats/jasp-test-release/issues/2486
fixes https://github.com/jasp-stats/jasp-test-release/issues/2487
fixes https://github.com/jasp-stats/jasp-test-release/issues/2488
fixes https://github.com/jasp-stats/jasp-test-release/issues/2520
Regarding https://github.com/jasp-stats/jasp-test-release/issues/2488, I was only able to fix the "leading minor of order ... is not positive"; I was not able to reproduce the bootstrapping error.
=> Release fixes

inst/qml/CorrelationBayesian.qml
Fixes https://github.com/jasp-stats/jasp-issues/issues/42
=> Change Bayes factor label according to the hypothesis value

R/regressionlogistic.R, inst/qml/RegressionLogistic.qml
Plot independent variables against logit predicted probabilities
=> add linearity plot logistic regression

R/regressionlogistic.R
It solves the symptom of https://github.com/jasp-stats/jasp-issues/issues/1984, 
but it does not solve the cause (one analysis influences another)
=> Fix footnote issue

R/regressionlinearbayesian.R, inst/qml/Correlation.qml, inst/qml/CorrelationBayesian.qml, inst/qml/RegressionLinear.qml, inst/qml/RegressionLinearBayesian.qml, inst/qml/RegressionLogistic.qml, inst/qml/RegressionLogisticBayesian.qml
=>  bayes lin reg read all as numeric

R/commonglm.R
before it did not account for missingness when showing the casenumbers
relevant line [here](https://github.com/jasp-stats/jaspRegression/pull/347/files#diff-e69ace5d5a9cd6c06d8804b9c6575675668ccb962851b893081a3575395a5393R862)
=> Casewise table handles missinginess

R/commonglm.R, R/generalizedlinearmodel.R, R/regressionlogistic.R
- nTrials should be non-zero in binomial GLM
Fix https://github.com/jasp-stats/jasp-test-release/issues/2757
- don't try to plot estimates when the best model has no predictors in logistic regression
Fix https://github.com/jasp-stats/jasp-test-release/issues/2755
- more informative error when confints cannot be calculated
Fix https://github.com/jasp-stats/jasp-test-release/issues/2756
=> Regression bug fixes

R/regressionlinear.R
Fix https://github.com/jasp-stats/INTERNAL-jasp/issues/2704 
Also improve ready check
=> [Linear regression] Only check weights cov when there are predictors

R/correlation.R
Fixes https://github.com/jasp-stats/jasp-issues/issues/3077
=> Do not translate italic

inst/qml/RegressionLogistic.qml, tests/testthat/test-regressionlogistic.R, tests/testthat/test-regressionlogisticVerification.R
since they are quite central in logistic regression
=> [Logistic Regression] odds ratios by default 

R/commonglm.R, R/generalizedlinearmodel.R, R/regressionlinear.R, R/regressionlinearbayesian.R, R/regressionlogistic.R, R/regressionlogisticbayesian.R, inst/qml/GeneralizedLinearModel.qml, inst/qml/RegressionLinear.qml, inst/qml/RegressionLinearBayesian.qml, inst/qml/RegressionLogistic.qml, inst/qml/RegressionLogisticBayesian.qml, inst/qml/common/ExportBayesian.qml, inst/qml/common/ExportFreq.qml, inst/qml/common/GlmInputComponent.qml, inst/qml/common/OutlierComponent.qml
also in bayesian analysis, in new tab called "Export"
"counts" variable in glm - binomial now is a scale variable rather than nominal (just like in counts for contingency table)
Fix https://github.com/jasp-stats/jasp-issues/issues/3389 
Fix https://github.com/jasp-stats/INTERNAL-jasp/issues/2823 
Fix https://github.com/jasp-stats/jasp-issues/issues/2240
=> save residuals and predictions

R/correlation.R, R/regressionlinear.R, R/regressionlogistic.R, inst/qml/common/GlmInputComponent.qml, inst/qml/common/OutlierComponent.qml
Fix https://github.com/jasp-stats/jasp-test-release/issues/2928
Fix https://github.com/jasp-stats/jasp-test-release/issues/2963
Fix https://github.com/jasp-stats/jasp-test-release/issues/2960
Fix https://github.com/jasp-stats/jasp-test-release/issues/2956
Fix https://github.com/jasp-stats/jasp-test-release/issues/2963
=> Fix error messages in regression 

DESCRIPTION, R/commonglm.R, R/hmeasure.R, renv.lock
@RensDofferhoff Let's wait for CI before merging.
=> Copy relevant functions from 'hmeasure'

inst/qml/common/GlmInputComponent.qml
fixes: https://github.com/jasp-stats/jasp-issues/issues/3681
also fixes the variable input scale, the one restricted to 370 looks horrendous, why that?
=> Fix glm input
