jasp-stats/jaspRegression

R/regressionlogistic.R
Copy of https://github.com/jasp-stats/jasp-desktop/pull/4313 and adds `jaspBase::` in some places
=> fix bootstrap in logistic regression

R/regressionlinearbayesian.R, inst/qml/RegressionLinearBayesian.qml
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1160
From `?BAS::bas.lm`:
```r
alpha: optional hyperparameter in g-prior or hyper g-prior. 
```
But until now you couldn't specify the value of alpha if you selected the g-prior. It was also ignored in the R code. 
UI before:
UI after:
I'm not sure why the input for alpha isn't aligned with the options g-prior, but that was already the case before as well.
=> Don't ignore alpha for g-priors

R/commoncor.R, R/correlationbayesian.R, tests/figs/CorrelationBayesian/correlationbayesian-bayesian-correlation-matrix-plot-with-ranks-subplot-1.svg, tests/figs/CorrelationBayesian/correlationbayesian-bayesian-correlation-matrix-plot-with-ranks-subplot-2.svg, tests/figs/CorrelationBayesian/correlationbayesian-bayesian-correlation-matrix-plot-with-ranks-subplot-3.svg, tests/figs/CorrelationBayesian/correlationbayesian-bayesian-correlation-matrix-plot-with-ranks-subplot-4.svg, tests/figs/CorrelationBayesian/correlationbayesian-bayesian-correlation-matrix-plot-with-ranks-subplot-5.svg, tests/figs/CorrelationBayesian/correlationbayesian-scatterplot-with-ranks.svg, tests/testthat/test-correlationbayesian.R
Fixes https://github.com/jasp-stats/jasp-issues/issues/1081
1. Shows "Ranks of xxx" as axes titles when a plot is showing ranks.
2. Fixes the dependencies, so that when Pearson is no longer checked or selected, the descriptives plot is updated accordingly.
3. Adds unit tests for the figures with ranks.
=> Bayesian correlation: Explicitly show "Ranks of ..." when plotting ranks

DESCRIPTION, R/regressionlinearbayesian.R, tests/figs/RegressionLinearBayesian/regressionlinearbayesian-posteriorcoefficientswithcri.svg, tests/figs/jasp-deps.txt, tests/testthat/test-regressionlinearbayesian.R
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1297
For some reason, in https://github.com/jasp-stats/jasp-desktop/pull/2375 I thought it was a good idea to use `eps.correct = 2`. But that gives for some intervals:
```r
confInt <- c(-0.497306096, 0.104727599)
> pretty(confInt, eps.correct = 0) # new behavior
[1] -0.5 -0.4 -0.3 -0.2 -0.1  0.0  0.1  0.2
> pretty(confInt, eps.correct = 2) # old behavior
[1] -5.000000e-01 -4.000000e-01 -3.000000e-01 -2.000000e-01 -1.000000e-01 -5.551115e-17  1.000000e-01
[8]  2.000000e-01
```
`eps.correct = 0` is clearly preferred (and is also R's default) so I changed this.
Also:
- added a unit test for this plot, because there was none.
- reverted https://github.com/jasp-stats/jaspRegression/pull/36 in favor of …
=> Avoid scientific notation in the axes of plots

R/regressionlinear.R
Fixes https://github.com/jasp-stats/jasp-issues/issues/1333
The covariance check should not consider the dependent variable, because the ols estimate only does something like
```r
beta = solve(x %*% t(x)) %*% x %*% t(y)
```
So it mainly matters that `x` is in good shape. The only real change is the `target` variable.
=> Relax error check on covariance matrix

R/regressionlogistic.R, inst/qml/RegressionLogistic.qml
Fixes jasp-stats/INTERNAL-jasp/issues/1395:
- Took away the "Display", such that it now only says "Conditional estimates plot".
- Changed to y-axis label to non-italic.
@Kucharssim feedback on the whole git-workflow is highly appreciated! Did I do this correctly this time? Also is it necessary/ advisable to split it into several commits, as I did now, or would this usually be done within a single commit?
=> Adjusted conditional estimates plot

DESCRIPTION, R/commonglm.R, R/regressionlinear.R, R/regressionlogistic.R
I removed the dependency of the car package, because this dependency causes JASP to crash when loading it in the developer mode in Windows 10. I did so, by coping the car::durbinWatsonTest and car::vif functions from the source code of car and pasting them in the commonglm.R file. Where needed, I then directly called these functions.
=> removed dependency of the car package

.Rbuildignore, R/regressionlinearbayesian.R, inst/qml/RegressionLinearBayesian.qml, tests/testthat/test-regressionlinearbayesian.R
Fixes https://github.com/jasp-stats/jasp-issues/issues/1596
I'm not 100% sure how intuitive the dependency between exporting the residuals and the model type is:
but I'm open to suggestions. @amirmasoudabdol if you have any ideas, feel free to chime in!
Also, since this is for 0.17, feel free to approve when you're happy but please do not merge before 0.16.1 is released.
=> Bayesian linear regression now exports residuals and residual sds

DESCRIPTION, R/glmClassical.R, R/glmCommonFunctions.R, inst/qml/GeneralizedLinearModel.qml, inst/qml/common/GlmInputComponent.qml, tests/testthat/test-generalizedlinearmodel.R
fixed https://github.com/jasp-stats/jasp-issues/issues/202
fixed https://github.com/jasp-stats/jasp-issues/issues/784
fixed https://github.com/jasp-stats/jasp-issues/issues/1345
=> added multinomial, ordinal and firth logistic regression

R/regressionlinear.R
Fixes https://github.com/jasp-stats/jasp-test-release/issues/2028
test file:
[Album_Sales.jasp.zip](https://github.com/jasp-stats/jaspRegression/files/10457554/Album_Sales.jasp.zip)
rename and drop .zip, issue should disappear upon refresh.
This is a very silly issue. `update(fit, formula = newFormula)` internally re-evaluates the call used to create the lm object ([e.g., here](https://github.com/jasp-stats/jaspRegression/blob/8d3c281ba5b91b88aca573195dd34b91977231b0/R/regressionlinear.R#L873)), but there the data object was called `data` so it tries to re-evaluate that and then notices that in the current scope there is no object called `data`.
=> Fix test issue

R/regressionlogisticbayesian.R
I always get confused what is passed to R when `AssignedVariablesList` is empty... Hence stupid bugs like this
=> fix bayes logistic footnote

R/commonglm.R, tests/testthat/test-regressionlogistic.R
fixes https://github.com/jasp-stats/jasp-issues/issues/2368
The bug was caused by a relatively large n which resulted in a numerical overflow. Now the core calculation is done on the log scale so it will be more robust.
=> make coxSnell and Nagelkerke computationally more robust

R/regressionlinear.R
There is a reported bug related to missing translations in the (frequentist) linear regression coefficient tables reported here: https://github.com/jasp-stats/jasp-issues/issues/2405, which should be fixed by this PR.
The issue is that the term "(Intercept)" is not translated in the JASP output. The challenge is that in the R code, the term "(Intercept)" is used at multiple places, e.g., in string comparisons. To avoid side effects, I propose to keep the term "(Intercept)" throughout the code as it is now and only translate right before the coefficient table is assembled. This is the least intrusive change to the code base, which fixes the problem.
Please independently review and test before merging. Thanks!
=> Bug fix for missing translation of term "(Intercept)" in regression coefficient table

R/regressionlinear.R
Fix https://github.com/jasp-stats/jasp-issues/issues/2597
=> More lenient error check stepwise regression with factors

R/regressionlinear.R
I was still testing the fixes in https://github.com/jasp-stats/jaspRegression/pull/288 and realized it still would break with interactions between factors (due to appending the factor level names). I see there is some stuff in regression already to deal with this, but the quick way is to now disallow interactions with > 1 factor variable (still more lenient than before). 
While fixing it I also found a bug in the coefficient table also related to this (I think) - see jasp file here (change ext to .jasp): 
[debugStepwise3.zip](https://github.com/jasp-stats/jaspRegression/files/14420223/debugStepwise3.zip), which this PR also resolves.
=> Disable factor interactions stepwise, and fix bug in coef table

R/regressionlogistic.R, inst/help/Correlation.md, tests/testthat/test-correlation.R
correlation uses it, so also update here
=> shapiro test changed in MANOVA

R/correlation.R, tests/testthat/test-correlation.R
Instead of footnotes, behave like all other analyses..
Fix https://github.com/jasp-stats/jasp-issues/issues/2747, by not relying on footnotes but on hasErrors
=> Add error check to correlation

inst/qml/GeneralizedLinearModel.qml
Makes it consistent with 0.18.3, to avoid the confusion in https://github.com/jasp-stats/jasp-issues/issues/2926
=> GLM - disable some tabs for other family

inst/qml/RegressionLogistic.qml
Previously the smallest step size in ROC plots was 0.05, now it's 0.001, to make it more like what is possible in R (see https://github.com/jasp-stats/jasp-issues/issues/3350 for an example)
=> More cut off steps ROC plots

R/regressionlinear.R, inst/qml/RegressionLinear.qml
Add checkbox to add linear terms of each covariate (not to interactions or factors) in the models:
As requested [here](https://support.jasp-services.com/SCG-Chemicals/SCG_Chemicals_Public_Company_Limited/issues/7). As it is now, it functions exactly the same as the quadratic terms in QC - Analyse design, with the "Full Quadratic option".
Equation table:
As requested [here](https://support.jasp-services.com/SCG-Chemicals/SCG_Chemicals_Public_Company_Limited/issues/8).
=> [Linear Regression] Add quadratic terms + equation table
